"""
"Ajouter des commentaires pedagogiques" dialog (AI tool).

2-column layout:
  - left column: current code (read-only, Arduino coloring),
  - right column: commented code generated by the AI (read-only),
  - switches via QStackedWidget to a "loading" page during the call.

Buttons: "Appliquer" (replaces the editor's code) + "Régénérer" +
"Fermer". Auto-launches the generation on opening.

The "Appliquer" button emits `apply_requested(str)`; it is StudioView that
handles the actual replacement (with confirmation and tracker reset).
"""
from __future__ import annotations

from PyQt6.QtCore import Qt, QThread, QTimer, pyqtSignal
from PyQt6.QtGui import QPalette, QColor
from PyQt6.QtWidgets import (
    QDialog, QHBoxLayout, QVBoxLayout, QLabel, QPushButton,
    QSizePolicy, QStackedWidget, QWidget,
)

from .code_editor import CodeEditor
from .i18n import lang_manager, Strings
from .robot_loader import RobotLoader, LoaderLabel
from .theme import (
    ColorScheme, theme_manager, primary_button_qss, secondary_button_qss,
)


class _AddCommentsWorker(QThread):
    finished = pyqtSignal(str)
    error    = pyqtSignal(str)

    def __init__(self, backend, code: str, language: str, board_name: str):
        super().__init__()
        self._backend    = backend
        self._code       = code
        self._language   = language
        self._board_name = board_name

    def run(self):
        try:
            text = self._backend.add_comments(
                self._code, self._language, self._board_name,
            )
            self.finished.emit(text)
        except Exception as e:
            self.error.emit(str(e))


class AddCommentsDialog(QDialog):
    """Modal "Ajouter des commentaires" dialog."""

    apply_requested = pyqtSignal(str)  # commented code accepted by the user

    def __init__(self, backend, code: str, board_name: str, parent=None):
        super().__init__(parent)
        self._backend = backend
        self._original_code = code
        self._board_name = board_name
        self._commented_code = ""
        self._worker: _AddCommentsWorker | None = None

        self.setModal(True)
        self.setMinimumSize(1000, 560)
        self._build(code)
        self.apply_theme(theme_manager.current)
        self.apply_lang(lang_manager.current)
        theme_manager.changed.connect(self.apply_theme)
        lang_manager.changed.connect(self.apply_lang)

        self._trigger_generate()

    # ── Construction ─────────────────────────────────────────────
    def _build(self, code: str):
        root = QVBoxLayout(self)
        root.setContentsMargins(16, 16, 16, 12)
        root.setSpacing(10)

        cols = QHBoxLayout()
        cols.setSpacing(12)
        root.addLayout(cols, stretch=1)

        # ── Left column: original code ───────────────────────
        left_col = QVBoxLayout()
        left_col.setSpacing(4)
        self._lbl_original = QLabel()
        left_col.addWidget(self._lbl_original)
        self._original_view = CodeEditor()
        self._original_view.setPlainText(code)
        self._original_view.setReadOnly(True)
        self._original_view.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding,
        )
        left_col.addWidget(self._original_view, stretch=1)
        cols.addLayout(left_col, stretch=1)

        # ── Right column: commented code (with loading stack) ─
        right_col = QVBoxLayout()
        right_col.setSpacing(4)
        self._lbl_commented = QLabel()
        right_col.addWidget(self._lbl_commented)

        self._commented_view = CodeEditor()
        self._commented_view.setReadOnly(True)
        self._commented_view.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding,
        )

        self._loading_page = QWidget()
        loading_layout = QVBoxLayout(self._loading_page)
        loading_layout.setContentsMargins(0, 0, 0, 0)
        loading_layout.setSpacing(8)
        loading_layout.addStretch(1)
        self._robot = RobotLoader(point_size=18)
        loading_layout.addWidget(self._robot, alignment=Qt.AlignmentFlag.AlignHCenter)
        self._lbl_loading_text = LoaderLabel(point_size=10)
        self._lbl_loading_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        loading_layout.addWidget(self._lbl_loading_text)
        loading_layout.addStretch(1)

        self._right_stack = QStackedWidget()
        self._right_stack.addWidget(self._commented_view)  # 0
        self._right_stack.addWidget(self._loading_page)    # 1
        right_col.addWidget(self._right_stack, stretch=1)
        cols.addLayout(right_col, stretch=1)

        # ── Action bar ─────────────────────────────────────
        actions = QHBoxLayout()
        actions.setSpacing(8)
        self._btn_apply = QPushButton()
        self._btn_apply.setCursor(Qt.CursorShape.PointingHandCursor)
        self._btn_apply.setEnabled(False)
        self._btn_apply.clicked.connect(self._on_apply)
        actions.addWidget(self._btn_apply)
        self._btn_rerun = QPushButton()
        self._btn_rerun.setCursor(Qt.CursorShape.PointingHandCursor)
        self._btn_rerun.clicked.connect(self._trigger_generate)
        actions.addWidget(self._btn_rerun)
        actions.addStretch(1)
        self._btn_close = QPushButton()
        self._btn_close.setCursor(Qt.CursorShape.PointingHandCursor)
        self._btn_close.clicked.connect(self.reject)
        actions.addWidget(self._btn_close)
        root.addLayout(actions)

    # ── AI trigger ───────────────────────────────────────────
    def _trigger_generate(self):
        if self._worker is not None and self._worker.isRunning():
            return
        self._btn_apply.setEnabled(False)
        self._btn_rerun.setEnabled(False)
        self._set_spinner_visible(True)
        self._worker = _AddCommentsWorker(
            self._backend, self._original_code,
            lang_manager.ai_lang_name(), self._board_name,
        )
        self._worker.finished.connect(self._on_done)
        self._worker.error.connect(self._on_error)
        self._worker.start()

    def _on_done(self, text: str):
        self._commented_code = text.rstrip() + "\n"
        self._commented_view.setPlainText(self._commented_code)
        self._btn_apply.setEnabled(True)
        self._btn_rerun.setEnabled(True)
        self._set_spinner_visible(False)

    def _on_error(self, msg: str):
        self._commented_view.setPlainText(f"⚠ {msg}")
        self._btn_apply.setEnabled(False)
        self._btn_rerun.setEnabled(True)
        self._set_spinner_visible(False)

    def _on_apply(self):
        if self._commented_code:
            self.apply_requested.emit(self._commented_code)
            self.accept()

    # ── Loader ────────────────────────────────────────────────────
    def _set_spinner_visible(self, visible: bool):
        if visible:
            self._right_stack.setCurrentWidget(self._loading_page)
            self._robot.start()
            self._lbl_loading_text.start()
        else:
            self._robot.stop()
            self._lbl_loading_text.stop()
            self._right_stack.setCurrentWidget(self._commented_view)

    # ── Theme / Language ───────────────────────────────────────────
    def apply_theme(self, c: ColorScheme):
        p = self.palette()
        p.setColor(QPalette.ColorRole.Window, QColor(c.main_bg))
        self.setPalette(p)
        self.setAutoFillBackground(True)
        lbl_style = (
            f"font-size: 10pt; font-weight: 600; color: {c.text_primary};"
            "background: transparent;"
        )
        self._lbl_original.setStyleSheet(lbl_style)
        self._lbl_commented.setStyleSheet(lbl_style)
        # "Apply" = primary (filled); "Regenerate" + "Close" =
        # secondary (outlined). Agreed centralized style (green on hover).
        primary = primary_button_qss(c, padding="6px 16px")
        secondary = secondary_button_qss(c, padding="6px 16px")
        self._btn_apply.setStyleSheet(primary)
        self._btn_rerun.setStyleSheet(secondary)
        self._btn_close.setStyleSheet(secondary)
        # Spinner + loading text: phosphor GREEN (signal_ok), not
        # nav_active_bg which is nearly invisible (very dark/pale green).
        self._robot.set_color(c.signal_ok)
        self._lbl_loading_text.set_color(c.signal_ok)
        self._loading_page.setStyleSheet(
            f"background-color: {c.sidebar_bg}; border-radius: 6px;"
        )

    def apply_lang(self, s: Strings):
        self.setWindowTitle(s.studio_addcmt_title)
        self._lbl_original.setText(s.studio_addcmt_original)
        self._lbl_commented.setText(s.studio_addcmt_commented)
        self._btn_apply.setText(s.studio_addcmt_apply)
        self._btn_rerun.setText(s.studio_addcmt_rerun)
        self._btn_close.setText(s.studio_explain_close)
        self._lbl_loading_text.set_text(s.studio_addcmt_loading)
